---
title: "Bulle d'R n°1 : Bonnes pratiques à ETTIS"
date: "2023-06-01"
date-format: long
lang: fr  
author:
  - name: Sandrine LYSER
    orcid: 0000-0001-6820-0672
    email: sandrine.lyser@inrae.fr
  - name: David CARAYON
    email: david.carayon@inrae.fr
    orcid: 0000-0003-0217-2175
format: 
  inrae-revealjs:
    footer: "Bulle d'R n°1 | Bonnes pratiques"
    # theme: [custom.scss]
    transition: none
revealjs-plugins:
  - pointer
from: markdown+emoji
---

## Présentation : Bulle d'R, concept, mattermost

## Introduction R -  Rstudio 

Cf. TWIX qui sera disponible ce lien : *lien TWIX* (S)


## Rappel sur les projets : RProject (D)

	1) Architectures : simple à compliqué 
	2) InraeThemes : Un template proposé

## Importer ses données (S)
	1) Le concept de données tidy
	2) Importer proprement ses données (xlsx, csv)
	3) Viewxl : pour vérifier son import ou explorer

## Conventions de nommage (S)
	1) Fichiers : explicites, milésimés, numérotés
	2) Pour les variables : snakeCase, CamelCase 
	
##  Gestion des packages (D)
	1) Version de R : Quelques gros changements (> 4)
	2) Rappel sur le fonctionnement des packages : install / library
	3) Prefixage :: (conflits etc.)
	4) Le tidyverse *vs* base

##  Structuration des scripts (S)
	1) Esquisse, FactoShiny... Reproductibilité => Stocker le code dans 1 script quand même
	2) Packages + session_info pour les versions
	3) Créer des sections : CTRL + MAJ + R (+ addin)
	4) Commentaires
	5) Aller plus loin : CompileReport et/ou Programmation lettrée (Rmd) => Session dédiée (si interêt)

##  L'export (hors Rmd) (S)
	1) Les plots (base + ggplot)
	2) Les tableaux :  XLSX / CSV
	3) Packages export auto : dataExplorer

##  Quelques packages conseils (D)
	1) questionr
	2) skimr
	3) easystats
	4) ggstatsplots
	5) FactoMineR + factoextra pour le factoriel + PCAmixdata

##  Pour aller (beaucoup) plus loin (D)
	1) Rmd / Quarto
	2) Renv
	3) git

##  La suite ? avec les liens 